config/routes.rb
Polltest::Application.routes.draw do
      
  resources :votings

  root "votings#index"
  
  get "/home", to: "pages#home", as: "home"
  
end

app/models/voting.rb
class Voting < ActiveRecord::Base
    validates_presence_of :vote, :party
    validates_format_of :postcode, :multiline => true, :with =>  /^([A-PR-UWYZ]([0-9]{1,2}|([A-HK-Y][0-9]|[A-HK-Y][0-9]([0-9]|[ABEHMNPRV-Y]))|[0-9][A-HJKS-UW])\s?[0-9][ABD-HJLNP-UW-Z]{2}|(GIR\ 0AA)|(SAN\ TA1)|(BFPO\ (C\/O\ )?[0-9]{1,4})|((ASCN|BBND|[BFS]IQQ|PCRN|STHL|TDCU|TKCA)\ 1ZZ))$$/i, :message => "invalid postcode", :on => :create
    before_save :get_parliamentary
    scope :voted,  -> { where(vote: true) }
    
    
    def get_parliamentary
      postcode = self.postcode.delete(' ')
      response = HTTParty.get("http://api.postcodes.io/postcodes/#{postcode}").parsed_response
      if response["status"] == 200
      self.parliamentary = response["result"]["parliamentary_constituency"]
      else
          puts "error"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
end

app/controllers/votings_controller.rb
class VotingsController < ApplicationController
  before_action :set_voting, only: [:show, :edit, :update, :destroy]

  # GET /votings
  # GET /votings.json
  def index
    @votings = Voting.all
    @data = Voting.voted
    @votes = @data.group_by {|k| k[:parliamentary] }
  end

  # GET /votings/1
  # GET /votings/1.json
  def show
  end

  # GET /votings/new
  def new
    @voting = Voting.new
  end

  # GET /votings/1/edit
  def edit
  end

  # POST /votings
  # POST /votings.json
  def create
    @voting = Voting.new(voting_params)

    respond_to do |format|
      if @voting.save
        format.html { redirect_to votings_path, notice: 'Voting was successfully created.' }
        format.json { render :index, status: :created, location: @voting }
      else
        format.html { render :new }
        format.json { render json: @voting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votings/1
  # PATCH/PUT /votings/1.json
  def update
    respond_to do |format|
      if @voting.update(voting_params)
        format.html { redirect_to @voting, notice: 'Voting was successfully updated.' }
        format.json { render :show, status: :ok, location: @voting }
      else
        format.html { render :edit }
        format.json { render json: @voting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votings/1
  # DELETE /votings/1.json
  def destroy
    @voting.destroy
    respond_to do |format|
      format.html { redirect_to votings_url, notice: 'Voting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voting
      @voting = Voting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voting_params
      params.require(:voting).permit(:postcode, :parliamentary, :party, :vote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | Polltest"      
    end
  end
end

app/helpers/email_helper.rb
module EmailHelper
  def line_break(s)
    s.gsub("\n", "<br/>") 
  end
end

app/helpers/votings_helper.rb
module VotingsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to "Votes", votings_path %></li>
<li><%= link_to "New Vote", new_voting_path%></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Polltest" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
            <%= yield(:script)%>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      
    <div class="container">
       
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>

        </div>     
      </div>  
      
    </div>
  </div>
    
  <%= render 'layouts/footer' %>    

</body>
</html>

app/views/pages/home.html.erb
<% title("Home Page") %>
<h1><i class="fa fa-home"></i> Home Page <small>views/pages/home.html.erb</small></h1>

app/views/votings/_form.html.erb
<%= simple_form_for(@voting, html: { class: 'form-horizontal' } )do |f| %>
  <% if @voting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voting.errors.count, "error") %> prohibited this voting from being saved:</h2>

      <ul>
      <% @voting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :postcode %>
   	<%= f.input :vote, as: :boolean, checked_value: true, unchecked_value: false, label: "Are you going to vote?" %>
    <%= f.input :party, priority: [ "Labour" ], collection: [ "Labour", "Conservatives", "Liberal", "Democratic" ], label: "Which Party?" %>
  <div class="actions">
    <%= f.submit "Enter", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/votings/index.html.erb
<%=content_for :script do %>
<%=javascript_include_tag "chartkick"%>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%end%>
<div class="btn-group btn-group-justified"
</div>
<h1>Overall Party Votes: <%= @data.count%></h1>
<p id="notice"><%= notice %></p>
<div class="container">
	<div class="row">
		<div class="col-md-7">
			<%= pie_chart @votings.group(:party).count%>
		</div>
		<div class="col-md-6">
			<h1>Votes By parliamentary area</h1>
			<% @votes.each do |f, t| %>
			<a><p class="bg-primary"><strong><%= f.humanize%> vote count: <%=t.count%></strong></p></a>
			<% data = Hash[t.map {|a| [a.party, t.select {|b| b["party"] == a.party}.count  ]}]%>
			<%=bar_chart data %>
			</br>
			</ul>
			</li>
			<% end %>
		</div>
	</div>
</div>

app/views/votings/new.html.erb
<h1>New Voting</h1>

<%= render 'form' %>

<%= link_to 'Back', votings_path %>

app/views/votings/show.html.erb
<%=content_for :script do %>
<%=javascript_include_tag "chartkick"%>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%end%>


<div class="container">
	<div class="row">
		<div class="col-md-6">
		<%= pie_chart Voting.group(:party).count%>
		</div>
	</div>
</div>



<p id="notice"><%= notice %></p>

<p>
  <strong>Postcode:</strong>
  <%= @voting.postcode %>
</p>

<p>
  <strong>Parliamentary:</strong>
  <%= @voting.parliamentary %>
</p>

<p>
  <strong>Party:</strong>
  <%= @voting.party %>
</p>

<p>
  <strong>Vote:</strong>
  <%= @voting.vote %>
</p>

<%= link_to 'Edit', edit_voting_path(@voting) %> |
<%= link_to 'Back', votings_path %>